export const IDENTIFIER = {
  Logger: Symbol.for('Logger'),
  Application: Symbol.for('Application'),
  HttpService: Symbol.for('HttpService'),
  MongooseService: Symbol.for('MongooseService'),
  PasswordService: Symbol.for('PasswordService'),
  Routes: Symbol.for('Routes'),
  BasicMiddleware: Symbol.for('BasicMiddleware'),
  ValidateMiddleware: Symbol.for('ValidateMiddleware'),
  ErrorHandlerMiddleware: Symbol.for('ErrorHandlerMiddleware'),
  UserRoutes: Symbol.for('UserRoutes'),
  UserRepository: Symbol.for('UserRepository'),
  UserController: Symbol.for('UserController'),
  UserService: Symbol.for('UserService'),
  HobbyRoutes: Symbol.for('HobbyRoutes'),
  HobbyService: Symbol.for('HobbyService'),
  HobbyRepository: Symbol.for('HobbyRepository'),
  HobbyController: Symbol.for('HobbyController'),
}